import { defineConfig, devices } from '@playwright/test';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({
  path: path.resolve(__dirname, '.env')
});

/**
 * QA DEBUG CONFIG
 *
 * Firefox är tillfälligt avstängt eftersom Playwright
 * inte kan starta Firefox lokalt:
 *
 * "Could not find profile folder"
 *
 * Chromium och WebKit fungerar.
 *
 * Authenticated tests reuse the session generated by the
 * setup project to avoid repeated logins for the same account.
 */
export default defineConfig({
  testDir: './tests',

  fullyParallel: false,

  forbidOnly: !!process.env.CI,

  retries: process.env.CI ? 2 : 0,

  workers: 1,

  reporter: 'html',

  use: {
    trace: 'on-first-retry',
  },

  projects: [
    {
      name: 'setup',
      testMatch: /.*\.setup\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        storageState: undefined,
      },
    },

    {
      name: 'chromium',
      dependencies: ['setup'],
      testIgnore: /auth\/.*\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'playwright-auth/user.json',
      },
    },

    {
      name: 'webkit',
      dependencies: ['setup'],
      testIgnore: /auth\/.*\.spec\.ts/,
      use: {
        ...devices['Desktop Safari'],
        storageState: 'playwright-auth/user.json',
      },
    },

    {
      name: 'chromium-auth',
      testMatch: /auth\/login\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'webkit-auth',
      testMatch: /auth\/login\.spec\.ts/,
      use: {
        ...devices['Desktop Safari'],
      },
    },

    {
      name: 'chromium-register',
      testMatch: /auth\/register\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'webkit-register',
      testMatch: /auth\/register\.spec\.ts/,
      use: {
        ...devices['Desktop Safari'],
      },
    },

    {
      name: 'chromium-session',
      testMatch: /auth\/session-resilience\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'webkit-session',
      testMatch: /auth\/session-resilience\.spec\.ts/,
      use: {
        ...devices['Desktop Safari'],
      },
    },

    {
      name: 'chromium-logout',
      testMatch: /auth\/logout\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'webkit-logout',
      testMatch: /auth\/logout\.spec\.ts/,
      use: {
        ...devices['Desktop Safari'],
      },
    },

    // Tillfälligt avstängd
    // {
    //   name: 'firefox',
    //   use: {
    //     ...devices['Desktop Firefox'],
    //   },
    // },
  ],
});